// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.CliArgsParser.Generators.Helpers;
using CodeOfChaos.GeneratorTools;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;

namespace CodeOfChaos.CliArgsParser.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[Generator(LanguageNames.CSharp)]
public class CommandGenerator : IIncrementalGenerator  {

    // -----------------------------------------------------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------------------------------------------------
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValueProvider<ImmutableArray<CommandDto>> data = context.SyntaxProvider.CreateSyntaxProvider(
            Predicate,
            Transform
        )
        .Where(dto => dto is not null)
        .Collect()!;
        
        context.RegisterSourceOutput(context.CompilationProvider.Combine(data), GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken ct) {
        return node is ClassDeclarationSyntax or RecordDeclarationSyntax;
    }

    private static CommandDto? Transform(GeneratorSyntaxContext context, CancellationToken ct) {
        SemanticModel semanticModel = context.SemanticModel;

        INamedTypeSymbol? symbol = context.Node switch {
            ClassDeclarationSyntax classDeclaration => semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol,
            RecordDeclarationSyntax recordDeclaration => semanticModel.GetDeclaredSymbol(recordDeclaration) as INamedTypeSymbol,
            _ => null
        };
        if (symbol is null) return null;
        if (!symbol.HasInterfaceWithDisplayName(TypeNames.ICliCommandInterface)) return null;
        return CommandDto.TryCreate(symbol);
    }
    
    private static void GenerateSources(SourceProductionContext context, (Compilation Compilation, ImmutableArray<CommandDto> Data) Box) {
        Compilation compilation = Box.Compilation;
        ImmutableArray<CommandDto> data = Box.Data;
        var builder = new GeneratorStringBuilder();

        foreach (CommandDto dto in data) {
            dto.CreatePartialClass(builder);
            context.AddSource($"{dto.ClassName}.g.cs", builder.ToStringAndClear());
        }

        builder.AppendAutoGenerated();
        builder.AppendUsings(
            "System",
            "System.Threading",
            "System.Threading.Tasks",
            "CodeOfChaos.CliArgsParser"
        );
        
        string containingAssemblyName = data.ElementAtOrDefault(0)?.Symbol.ContainingAssembly.Name ?? "UNDEFINED";
        builder.AppendNamespace(containingAssemblyName);
        builder.AppendLine();
        builder.AppendLine($"public static class __{containingAssemblyName.Replace(".", "")}__CliArgsParserDictionary {{");
        builder.AppendLineIndented("public static readonly Dictionary<string, Type> Commands = new Dictionary<string, Type>() {");
        builder.ForEachAppendLineIndented(data, dto => $"    {{ {dto.Name}, typeof({dto.Symbol.ToDisplayString()}) }},");
        builder.ForEachAppendLineIndented(data, dto => $"    {{ {dto.ShortName}, typeof({dto.Symbol.ToDisplayString()}) }},");
        builder.AppendLineIndented("};");
        builder.AppendLine("}");
        context.AddSource($"{containingAssemblyName}CliArgsParser.g.cs", builder.ToStringAndClear());
    }
    
}
